"""
Workflow nodes.

Every function in this module is a NODE FACTORY: it accepts an already
constructed application/rag service and returns a plain
``GraphState -> GraphState`` function suitable for
``StateGraph.add_node``. This is the dependency-injection seam for the
entire workflow package - node factories never construct their own
services, and the functions they return contain no business logic of
their own. Each node's body does exactly three things: read fields off
``GraphState``, call exactly one existing service method, and fold the
result back into a new ``GraphState`` via ``model_copy``.

Design decision:
    The seven SDLC agent nodes are generated by one private helper,
    ``_build_agent_node``, rather than seven near-identical copies of
    the same fifteen lines. This is not a violation of "one node per
    workflow step" - each requested node still exists as its own named,
    independently importable factory function - it is simply
    Don't-Repeat-Yourself applied to their shared implementation, which
    is itself a SOLID (Open/Closed) concern: adding an eighth agent node
    in the future means adding one three-line wrapper, not copying and
    re-verifying fifteen lines of dispatch/error-handling logic.

    Node names in this module are aligned to the actual ``AgentType``
    enum values implemented in the Agent Foundation package
    (requirements, architecture, planning, coding, testing,
    documentation, review). No ``deployment_agent_node`` is implemented,
    because no deployment/DevOps agent exists in that package - adding
    one here would mean either fabricating agent behavior inside the
    workflow layer (forbidden: workflows must not implement agent logic)
    or silently mislabeling another agent, both of which were rejected.
    This is called out explicitly rather than papered over.
"""

import logging
from collections.abc import Callable

from app.agents.models import AgentType
from app.application.agent_router import AgentRouter
from app.application.exceptions import AgentRoutingError, IngestionServiceError
from app.application.ingestion_service import IngestionService
from app.application.models import AgentRequest
from app.rag.exceptions import RAGError
from app.rag.models import RetrievalQuery
from app.rag.retriever import RetrieverService
from app.persistence.repositories import (
    WorkflowRunRepository,
    ArtifactRepository,
)
from app.workflows.state import (
    GraphState,
    RetrievedContextItem,
    WorkflowHistoryEntry,
    WorkflowPhase,
)

logger = logging.getLogger("codepilot.workflows.nodes")

WorkflowNode = Callable[[GraphState], GraphState]

# Maps each agent-producing phase to the key its output is stored under
# in `GraphState.generated_outputs`, and to the AgentType dispatched.
# Centralizing this mapping is what lets `_build_agent_node` stay a
# single, generic implementation.
_AGENT_PHASE_MAP: dict[AgentType, WorkflowPhase] = {
    AgentType.REQUIREMENTS: WorkflowPhase.REQUIREMENTS,
    AgentType.ARCHITECTURE: WorkflowPhase.ARCHITECTURE,
    AgentType.PLANNING: WorkflowPhase.PLANNING,
    AgentType.CODING: WorkflowPhase.CODING,
    AgentType.TESTING: WorkflowPhase.TESTING,
    AgentType.DOCUMENTATION: WorkflowPhase.DOCUMENTATION,
    AgentType.REVIEW: WorkflowPhase.REVIEW,
}


def _build_grounding_context(state: GraphState) -> str:
    """Assemble the grounding text available to an agent node so far.

    Combines retrieved chunk content with every output generated by
    earlier phases in this same execution, so later agents (e.g.,
    ``TestingAgent``) are grounded in both the original source
    documents and any requirements/architecture/code already produced
    earlier in the same workflow run. This is plain string
    concatenation over existing state fields - not prompt engineering,
    which remains entirely inside ``PromptBuilder``.

    Args:
        state: The current workflow state.

    Returns:
        str: The combined grounding text, or an empty string if no
        context is available yet.
    """
    sections: list[str] = []

    if state.retrieved_context:
        retrieved_text = "\n\n".join(item.content for item in state.retrieved_context)
        sections.append(f"--- Retrieved Source Context ---\n{retrieved_text}")

    for phase_key, content in state.generated_outputs.items():
        sections.append(f"--- Prior Output: {phase_key} ---\n{content}")

    return "\n\n".join(sections)


def _record_history(
    state: GraphState, phase: WorkflowPhase, summary: str, agent_type: AgentType | None = None
) -> list[WorkflowHistoryEntry]:
    """Build an updated conversation history list with one new entry appended.

    Args:
        state: The current workflow state.
        phase: The phase this history entry corresponds to.
        summary: Short human-readable summary of what happened.
        agent_type: The agent involved, if applicable.

    Returns:
        list[WorkflowHistoryEntry]: A new list equal to the existing
        history plus one new entry, ready to assign into an updated
        state.
    """
    entry = WorkflowHistoryEntry(phase=phase, agent_type=agent_type, summary=summary)
    return [*state.conversation_history, entry]


def ingest_documents_node(
    ingestion_service: IngestionService,
    workflow_run_repository: WorkflowRunRepository,
) -> WorkflowNode:
    """Build the node that ingests every document listed in workflow state.

    Args:
        ingestion_service: The existing application-layer service this
            node delegates all ingestion work to.
        workflow_run_repository: SQLite repository to track runs.

    Returns:
        WorkflowNode: A node function that ingests
        ``state.uploaded_documents`` and returns updated state.
    """

    def _node(state: GraphState) -> GraphState:
        errors = list(state.errors)
        ingested_count = 0

        for document in state.uploaded_documents:
            try:
                ingestion_service.ingest_document(
                    project_id=state.project_id,
                    file_path=document.file_path,
                    filename=document.filename,
                    document_type=document.document_type,
                )
                ingested_count += 1
            except IngestionServiceError as exc:
                logger.error(
                    "nodes.ingest_documents_failed",
                    extra={"project_id": state.project_id, "doc_filename": document.filename},
                )
                errors.append(f"Ingestion failed for '{document.filename}': {exc}")

        summary = f"Ingested {ingested_count}/{len(state.uploaded_documents)} document(s)."
        
        run_id = state.metadata.get("run_id")
        if run_id:
            workflow_run_repository.update_workflow_run(
                run_id=str(run_id),
                status="failed" if errors else "running",
                current_phase=WorkflowPhase.INGESTION.value,
                errors=errors,
            )

        return state.model_copy(
            update={
                "current_phase": WorkflowPhase.INGESTION,
                "errors": errors,
                "conversation_history": _record_history(state, WorkflowPhase.INGESTION, summary),
            }
        )

    return _node


def retrieve_context_node(
    retriever: RetrieverService,
    workflow_run_repository: WorkflowRunRepository,
    top_k: int = 5,
) -> WorkflowNode:
    """Build the node that retrieves grounding context for the workflow's prompt.

    Args:
        retriever: The existing RAG-layer service this node delegates
            all retrieval work to.
        workflow_run_repository: SQLite repository to track runs.
        top_k: Maximum number of chunks to retrieve.

    Returns:
        WorkflowNode: A node function that populates
        ``state.retrieved_context`` and returns updated state.
    """

    def _node(state: GraphState) -> GraphState:
        errors = list(state.errors)
        retrieved_items: list[RetrievedContextItem] = []

        if not state.user_prompt.strip():
            summary = "Skipped retrieval: no user_prompt was provided to search with."
        else:
            try:
                query = RetrievalQuery(
                    project_id=state.project_id, query_text=state.user_prompt, top_k=top_k
                )
                results = retriever.retrieve(query)
                retrieved_items = [
                    RetrievedContextItem(
                        content=result.content,
                        filename=result.metadata.filename,
                        chunk_index=result.metadata.chunk_index,
                        relevance_score=result.relevance_score,
                    )
                    for result in results
                ]
                summary = f"Retrieved {len(retrieved_items)} context chunk(s)."
            except RAGError as exc:
                logger.error(
                    "nodes.retrieve_context_failed",
                    extra={"project_id": state.project_id},
                )
                errors.append(f"Retrieval failed: {exc}")
                summary = "Retrieval failed."

        run_id = state.metadata.get("run_id")
        if run_id:
            workflow_run_repository.update_workflow_run(
                run_id=str(run_id),
                status="failed" if errors else "running",
                current_phase=WorkflowPhase.RETRIEVAL.value,
                errors=errors,
            )

        return state.model_copy(
            update={
                "current_phase": WorkflowPhase.RETRIEVAL,
                "retrieved_context": retrieved_items,
                "errors": errors,
                "conversation_history": _record_history(state, WorkflowPhase.RETRIEVAL, summary),
            }
        )

    return _node


def _build_agent_node(
    agent_router: AgentRouter,
    agent_type: AgentType,
    workflow_run_repository: WorkflowRunRepository,
    artifact_repository: ArtifactRepository,
) -> WorkflowNode:
    """Build a node that dispatches one SDLC agent via the existing router.

    Shared implementation backing every agent-specific node factory
    below. Not part of this module's public naming surface - each
    concrete agent still gets its own named factory function.

    Args:
        agent_router: The existing application-layer router this node
            delegates dispatch to.
        agent_type: Which agent this node dispatches to.
        workflow_run_repository: SQLite repository to track runs.
        artifact_repository: SQLite repository to persist artifacts.

    Returns:
        WorkflowNode: A node function that dispatches ``agent_type`` and
        folds its output into state.
    """
    phase = _AGENT_PHASE_MAP[agent_type]
    output_key = agent_type.value

    def _node(state: GraphState) -> GraphState:
        errors = list(state.errors)
        generated_outputs = dict(state.generated_outputs)

        request = AgentRequest(
            agent_type=agent_type,
            task_description=state.user_prompt or f"Perform the {output_key} phase.",
            project_id=state.project_id,
            document_context=_build_grounding_context(state) or None,
        )

        try:
            response = agent_router.dispatch(request)
            generated_outputs[output_key] = response.content
            summary = (
                f"{response.agent_name} produced {len(response.content)} character(s) of output."
            )
            # Persist artifact in SQLite after every agent execution
            artifact_repository.create_artifact(
                project_id=state.project_id,
                name=output_key,
                content_type="text/markdown",
                content=response.content,
            )
        except AgentRoutingError as exc:
            logger.error(
                "nodes.agent_dispatch_failed",
                extra={"agent_type": agent_type.value, "project_id": state.project_id},
            )
            errors.append(f"{agent_type.value} agent failed: {exc}")
            summary = f"{agent_type.value} agent dispatch failed."

        run_id = state.metadata.get("run_id")
        if run_id:
            workflow_run_repository.update_workflow_run(
                run_id=str(run_id),
                status="failed" if errors else "running",
                current_phase=phase.value,
                errors=errors,
            )

        return state.model_copy(
            update={
                "current_phase": phase,
                "selected_agent": agent_type,
                "generated_outputs": generated_outputs,
                "errors": errors,
                "conversation_history": _record_history(state, phase, summary, agent_type),
            }
        )

    return _node


def requirements_agent_node(
    agent_router: AgentRouter,
    workflow_run_repository: WorkflowRunRepository,
    artifact_repository: ArtifactRepository,
) -> WorkflowNode:
    """Build the node that dispatches the Requirements Agent.

    Args:
        agent_router: The existing application-layer router this node
            delegates dispatch to.
        workflow_run_repository: SQLite repository to track runs.
        artifact_repository: SQLite repository to persist artifacts.

    Returns:
        WorkflowNode: A node function that dispatches
        ``AgentType.REQUIREMENTS`` and returns updated state.
    """
    return _build_agent_node(agent_router, AgentType.REQUIREMENTS, workflow_run_repository, artifact_repository)


def architecture_agent_node(
    agent_router: AgentRouter,
    workflow_run_repository: WorkflowRunRepository,
    artifact_repository: ArtifactRepository,
) -> WorkflowNode:
    """Build the node that dispatches the Architecture Agent.

    Args:
        agent_router: The existing application-layer router this node
            delegates dispatch to.
        workflow_run_repository: SQLite repository to track runs.
        artifact_repository: SQLite repository to persist artifacts.

    Returns:
        WorkflowNode: A node function that dispatches
        ``AgentType.ARCHITECTURE`` and returns updated state.
    """
    return _build_agent_node(agent_router, AgentType.ARCHITECTURE, workflow_run_repository, artifact_repository)


def planning_agent_node(
    agent_router: AgentRouter,
    workflow_run_repository: WorkflowRunRepository,
    artifact_repository: ArtifactRepository,
) -> WorkflowNode:
    """Build the node that dispatches the Planning Agent.

    Args:
        agent_router: The existing application-layer router this node
            delegates dispatch to.
        workflow_run_repository: SQLite repository to track runs.
        artifact_repository: SQLite repository to persist artifacts.

    Returns:
        WorkflowNode: A node function that dispatches
        ``AgentType.PLANNING`` and returns updated state.
    """
    return _build_agent_node(agent_router, AgentType.PLANNING, workflow_run_repository, artifact_repository)


def coding_agent_node(
    agent_router: AgentRouter,
    workflow_run_repository: WorkflowRunRepository,
    artifact_repository: ArtifactRepository,
) -> WorkflowNode:
    """Build the node that dispatches the Coding Agent.

    Args:
        agent_router: The existing application-layer router this node
            delegates dispatch to.
        workflow_run_repository: SQLite repository to track runs.
        artifact_repository: SQLite repository to persist artifacts.

    Returns:
        WorkflowNode: A node function that dispatches
        ``AgentType.CODING`` and returns updated state.
    """
    return _build_agent_node(agent_router, AgentType.CODING, workflow_run_repository, artifact_repository)


def testing_agent_node(
    agent_router: AgentRouter,
    workflow_run_repository: WorkflowRunRepository,
    artifact_repository: ArtifactRepository,
) -> WorkflowNode:
    """Build the node that dispatches the Testing Agent.

    Args:
        agent_router: The existing application-layer router this node
            delegates dispatch to.
        workflow_run_repository: SQLite repository to track runs.
        artifact_repository: SQLite repository to persist artifacts.

    Returns:
        WorkflowNode: A node function that dispatches
        ``AgentType.TESTING`` and returns updated state.
    """
    return _build_agent_node(agent_router, AgentType.TESTING, workflow_run_repository, artifact_repository)


def documentation_agent_node(
    agent_router: AgentRouter,
    workflow_run_repository: WorkflowRunRepository,
    artifact_repository: ArtifactRepository,
) -> WorkflowNode:
    """Build the node that dispatches the Documentation Agent.

    Args:
        agent_router: The existing application-layer router this node
            delegates dispatch to.
        workflow_run_repository: SQLite repository to track runs.
        artifact_repository: SQLite repository to persist artifacts.

    Returns:
        WorkflowNode: A node function that dispatches
        ``AgentType.DOCUMENTATION`` and returns updated state.
    """
    return _build_agent_node(agent_router, AgentType.DOCUMENTATION, workflow_run_repository, artifact_repository)


def review_agent_node(
    agent_router: AgentRouter,
    workflow_run_repository: WorkflowRunRepository,
    artifact_repository: ArtifactRepository,
) -> WorkflowNode:
    """Build the node that dispatches the Review Agent.

    Args:
        agent_router: The existing application-layer router this node
            delegates dispatch to.
        workflow_run_repository: SQLite repository to track runs.
        artifact_repository: SQLite repository to persist artifacts.

    Returns:
        WorkflowNode: A node function that dispatches
        ``AgentType.REVIEW`` and returns updated state.
    """
    return _build_agent_node(agent_router, AgentType.REVIEW, workflow_run_repository, artifact_repository)


def save_output_node(workflow_run_repository: WorkflowRunRepository) -> WorkflowNode:
    """Build the node that finalizes a workflow execution.

    Marks the workflow as completed if it finished with no recorded
    errors, or failed if any step along the way recorded one. This node
    writes the final run status to the database.

    Args:
        workflow_run_repository: SQLite repository to track runs.

    Returns:
        WorkflowNode: A node function that marks the workflow complete
        or failed.
    """

    def _node(state: GraphState) -> GraphState:
        final_phase = WorkflowPhase.FAILED if state.errors else WorkflowPhase.COMPLETED
        summary = (
            f"Workflow failed with {len(state.errors)} error(s)."
            if state.errors
            else f"Finalized workflow with {len(state.generated_outputs)} output(s)."
        )
        
        run_id = state.metadata.get("run_id")
        if run_id:
            workflow_run_repository.update_workflow_run(
                run_id=str(run_id),
                status=final_phase.value,
                current_phase=final_phase.value,
                errors=state.errors,
            )

        return state.model_copy(
            update={
                "current_phase": final_phase,
                "conversation_history": _record_history(state, final_phase, summary),
            }
        )

    return _node